#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --help
bundle exec htmlproofer --internal-domains localhost:4000,pokemongo.si  --disable_external ./docs
